[project]
name = "phys-chatbot-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.122.0",
    "httpx>=0.28.1",
    "openai-agents>=0.6.1",
    "pydantic>=2.12.5",
]
